apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: testwithtrims-oct1
  janus-idp.io/tekton: testwithtrims-oct1
  backstage.io/kubernetes-id: testwithtrims-oct1
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: testwithtrims-oct1
resources: 
- initialize-namespace.yaml
- deployment-model-server.yaml
- service-model-server.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
